### ISSUE TITLE
update macos10.15.7

### ISSUE THREAD

**Issue by violin321** [zacks1990/hackintosh-3700x-rog470_i#1]
能更新一下oc efi文件吗，好像不能成功升级10.15.7

**Comment by zacks1990** [comment]
不好意思，已经换intel平台了，amd用不了随航。



------------------ Original ------------------

**Comment by violin321** [comment]
多谢回复，我已经找到了https://github.com/Purple-CSGO/Ryzen-3700x-X470i-Hackintosh-Opencore-EFI，这个好像换网卡之后也能用随航吧
